version: "3.1"

services:
  template:
    build: .
    restart: on-failure
    environment:
      TZ: Europe/Berlin
      PORT: 80
      HOST: localhost
      ENV: prod
      LOG_LEVEL: 1
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: template
      DATABASE_PASSWORD: postgres
      DATABASE: template
    ports:
      - 80:80
    depends_on:
      - database
      - redis
    networks:
      - evergene

  database:
    image: postgres:13.3
    restart: unless-stopped
    hostname: database
    volumes:
      # - ./data/db:/var/lib/postgresql/data
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: template
      POSTGRES_PASSWORD: postgres
    networks:
      - evergene

  redis:
    image: redis:6.2.5-alpine
    restart: unless-stopped
    networks:
      - evergene
    environment:
      TZ: Europe/Berlin
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

networks:
  evergene:
    external: true

volumes:
  db-data:
  redis-data:
  redis-conf:
